name: Docker image CI

on:
  push:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bagl3y/esphome-tesla-ble-bridge
          tags: |
            # Release tag (e.g. v1.2.3) and latest
            type=raw,enable=${{ github.event_name == 'release' }},value=${{ github.event.release.tag_name }}
            type=raw,enable=${{ github.event_name == 'release' }},value=latest
            # Nightly build on main: nightly-YYYYMMDD
            type=raw,enable=${{ github.event_name == 'push' }},value=nightly-{{date 'YYYYMMDD'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 